# Generated by Django 5.1.2 on 2024-11-20 07:14

import intro_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro_app', '0003_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('sent', 'Sent'), ('completed', 'Completed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[intro_app.models.positive]),
        ),
    ]
