# Generated by Django 5.1.2 on 2025-01-07 15:05

import intro_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intro_app', '0005_alter_customer_name_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[intro_app.models.positive]),
        ),
    ]
